version: "3"

includes:
  democmake:
    taskfile: "democmake/Taskfile.yml"

tasks:
  default:
    cmds:
      - task --list

  all:
    desc: "Run all tasks"
    cmds:
      - task: lint
      - task: test
      - task: build

  lint:
    desc: "Run linters"
    cmds:
      - echo "Running linters..."
      - echo "Linters completed."

  test:
    desc: "Run tests"
    cmds:
      - echo "Running tests..."
      - echo "Tests completed."

  build:
    desc: "Build the project"
    cmds:
      - echo "Building the project..."
      - task: democmake:build
      - echo 'this breaks because make is not in this container, we need to build in submodule continer'
      - echo "TODO also need to mount users git config to submodule container"
      - echo "Build completed."
