name: Create Release

on:
  push:
    branches:
      - release/* # Trigger on any branch starting with "release/"

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Load the VERSION from the env file
      - name: Load version
        run: |
          . ./VERSION.env
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Create a GitHub release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          body: "Automated release for version v${{ env.VERSION }}"
          draft: true
          prerelease: true
